use std::fs::File;
use std::io::Write;
use std::process::Command;
use quote::ToTokens;
use crate::{Config, Crate, Error, Lang};
#[cfg(not(feature = "cbindgen_only"))]
use crate::ast::Depunctuated;
#[cfg(not(feature = "cbindgen_only"))]
use crate::presentation::Fermentate;
use crate::presentation::RustFermentate;

pub trait IWriter {
    type Fermentate: ToTokens;
    fn write(&self, fermentate: Self::Fermentate) -> Result<(), Error>;
}

pub struct Writer {
    config: Config
}

impl From<Config> for Writer {
    fn from(config: Config) -> Self {
        Self { config }
    }
}
impl From<&Config> for Writer {
    fn from(config: &Config) -> Self {
        Self { config: config.clone() }
    }
}

impl IWriter for Writer {
    type Fermentate = RustFermentate;

    fn write(&self, fermentate: Self::Fermentate) -> Result<(), Error> {
        File::create(self.config.expansion_path())
            .map_err(Error::from)
            .and_then(|mut output| output.write_all(fermentate.to_token_stream().to_string().as_bytes())
                .map_err(Error::from))
    }
}

impl Writer {

    pub(crate) fn write_headers(&self) -> Result<(), Error> {
        // language = "C"
        // autogen_warning = "/* This file is autogenerated by cbindgen. Don't modify this manually. */"
        // braces = "SameLine"
        // cpp_compat = true
        // line_length = 80
        // tab_width = 4
        // documentation_style = "c"
        // style = "tag"
        // include_guard = "example_nested_h"
        // #swift_enum_macro = "CF_ENUM"
        //
        //     [parse]
        // parse_deps = true
        // include = ["ferment", "example-simple"]
        // extra_bindings = ["ferment", "example-simple"]
        //
        // [enum]
        // prefix_with_name = true
        //
        //
        // let includes = vec![
        //     "dash-spv-masternode-processor".to_string(),
        //     "rs-merk-verify-c-binding".to_string()
        // ];
        Command::new("mkdir")
            .args(&["-p", "target/include"])
            .status()?;

        // let crate_dir = env::var("CARGO_MANIFEST_DIR").map_err(Error::VarError)?;
        // println!("manifest: {}", crate_dir);
        // let bindings = cbindgen::generate_with_config(crate_dir, self.config.new_cbindgen_config())
        //     .map_err(Error::Cbindgen)?;
        // println!("bindings: {}", bindings.package_version);
        // if bindings.write_to_file(PathBuf::from(format!("target/include/{}.h", self.config.current_crate.name))) {
        //     Ok(())
        // } else {
        //     Err(Error::ExpansionError("bindings.write_to_file"))
        // }

        // env::var("CARGO_MANIFEST_DIR")
        //     .map_err(Error::VarError)
        //     .and_then(|crate_dir| cbindgen::generate_with_config(crate_dir, self.config.new_cbindgen_config())
        //         .map_err(Error::Cbindgen))
        //     .and_then(|bindings|
        //
        //     )
        //
        // env::var("CARGO_MANIFEST_DIR")
        //     .map(|crate_dir| cbindgen::generate_with_config(crate_dir))
        //
        // let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
        // let header = cbindgen::generate_with_config(crate_dir)
        // cbindgen::generate_with_config(&crate_dir, config)
        //     .unwrap()
        //     .write_to_file(format!("target/include/{framework}.h").as_str())

        let Config { current_crate: Crate { name: framework, .. }, languages, cbindgen_config_from_file, .. } = &self.config;
        #[allow(irrefutable_let_patterns)]
        let framework = languages.iter().find_map(|l| if let Lang::ObjC(conf) = l { Some(&conf.xcode.header_name) } else { None }).unwrap_or(framework);
       //  Command::new("mkdir")
       //      .args(&["-p", "target/include"])
       //      .status()?;
        Command::new("cbindgen")
            .args([
                "--config", cbindgen_config_from_file.as_ref().map(String::as_str).unwrap_or("cbindgen.toml"),
                "-o", format!("target/include/{framework}.h").as_str()
            ])
            .status()
            .map_err(Error::from)
            .map(|_| ())
    }
    #[cfg(not(feature = "cbindgen_only"))]
    pub fn write(&self, fermentate: Depunctuated<Fermentate>) -> Result<(), Error> {
        for f in fermentate {
            match f {
                Fermentate::Rust(fermentate) =>
                    IWriter::write(self, fermentate)?,
                #[cfg(feature = "objc")]
                Fermentate::ObjC(fermentate) => if let Some(config) = self.config.maybe_objc_config() {
                    crate::lang::objc::ObjCWriter::from(config)
                        .write(fermentate)?

                }
                _ => {}
            }
        }
        Ok(())
    }
}

