[package]
name = "ferment-macro"
version = "0.2.12"
description = "Macros for boilerplate"
edition = "2021"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.104", features = ["full", "visit-mut"] }
quote = "1.0.40"
