name: "CI"
inputs:
  toolchain:
    description: Rust toolchain to use, stable / nightly / beta, or exact version; uses rust-toolchain.toml if not specified
    default: ""
  target:
    description: Target Rust platform
    required: false
    default: x86_64-unknown-linux-gnu
  components:
    description: List of additional Rust toolchain components to install
    required: false
  cache:
    description: Enable Rust cache
    required: false
    default: "true"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "**" ]

jobs:
  lint:
    name: Format and Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

#      - name: rustfmt check
#        run: cargo fmt --all -- --check

      - name: clippy (selected crates)
        run: >
          cargo clippy
          -p ferment
          -p ferment-macro
          -p ferment-sys
          --all-targets --all-features -- -D warnings
